### ISSUE TITLE
williamyeh/ubuntu-trusty64-kubernetes

### ISSUE THREAD

**Issue by ravindar** [William-Yeh/docker-enabled-vagrant#1]
When trying to init and up williamyeh/ubuntu-trusty64-kubernetes I am unable to get the machine to start. Keep getting error about authentication failure when trying to connect.

Thanks
Ravindar

**Comment by William-Yeh** [comment]
Sorry but I haven't updated the k8s box for a long time.

I'll try to fix it recently.

**Comment by William-Yeh** [comment]
Fixed in https://github.com/William-Yeh/docker-enabled-vagrant/commit/faf3ba53dece82d18df45d3baedc288aaae31822

NOTE: The box name has changed to `williamyeh/k8s`.

TODO: Adjust details according to https://github.com/kubernetes/kubernetes/blob/v1.1.0/docs/getting-started-guides/scratch.md
