### ISSUE TITLE
docker-machine

### ISSUE THREAD

**Issue by MohamedQabbani** [William-Yeh/docker-enabled-vagrant#7]
When run this command: docker-machine create --driver virtualbox dev
I get the following error:
Error creating machine: Error with pre-create check: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

**Comment by William-Yeh** [comment]
You're trying to invoke `VBoxManage` from _inside_ the VirtualBox instance rather than from the host machine?
